create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  task text not null,
  done boolean not null default false,
  inserted_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.todos enable row level security;

create policy "public todos are readable"
on public.todos
for select
to anon
using (true);

create policy "public todos are insertable"
on public.todos
for insert
to anon
with check (true);

create policy "public todos are updateable"
on public.todos
for update
to anon
using (true)
with check (true);

create policy "public todos are deletable"
on public.todos
for delete
to anon
using (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'todos'
  ) then
    execute 'alter publication supabase_realtime add table public.todos';
  end if;
end;
$$;