version: '3'

tasks:
  default:
    cmds:
      - task --list-all

  format:
    cmds:
      - mvn spotless:apply

  compile:
    cmds:
      - mvn compile

  run:
    cmds:
      - mvn exec:java -Dexec.mainClass=com.example.App
