// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: books.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const analyzeBooks = `-- name: AnalyzeBooks :exec
ANALYZE books
`

func (q *Queries) AnalyzeBooks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, analyzeBooks)
	return err
}

const upsertBook = `-- name: UpsertBook :exec
INSERT INTO books (
	gutenberg_id,
	title,
	author,
	language,
	subjects,
	bookshelves,
	download_count,
	source_url,
	text_url,
	content,
	content_bytes,
	imported_at
)
OVERRIDING SYSTEM VALUE
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5::jsonb,
	$6::jsonb,
	$7,
	$8,
	$9,
	$10,
	$11,
	NOW()
)
ON CONFLICT (gutenberg_id)
DO UPDATE SET
	title = EXCLUDED.title,
	author = EXCLUDED.author,
	language = EXCLUDED.language,
	subjects = EXCLUDED.subjects,
	bookshelves = EXCLUDED.bookshelves,
	download_count = EXCLUDED.download_count,
	source_url = EXCLUDED.source_url,
	text_url = EXCLUDED.text_url,
	content = EXCLUDED.content,
	content_bytes = EXCLUDED.content_bytes,
	imported_at = NOW()
`

type UpsertBookParams struct {
	GutenbergID   int64
	Title         string
	Author        string
	Language      string
	Subjects      json.RawMessage
	Bookshelves   json.RawMessage
	DownloadCount int32
	SourceUrl     string
	TextUrl       string
	Content       string
	ContentBytes  int64
}

func (q *Queries) UpsertBook(ctx context.Context, arg UpsertBookParams) error {
	_, err := q.db.ExecContext(ctx, upsertBook,
		arg.GutenbergID,
		arg.Title,
		arg.Author,
		arg.Language,
		arg.Subjects,
		arg.Bookshelves,
		arg.DownloadCount,
		arg.SourceUrl,
		arg.TextUrl,
		arg.Content,
		arg.ContentBytes,
	)
	return err
}
