// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: demo.sql

package sqlc

import (
	"context"
)

const demoAggregateMetrics = `-- name: DemoAggregateMetrics :one
SELECT
	pdb.agg('{"avg": {"field": "download_count"}}')::text AS avg_downloads,
	pdb.agg('{"value_count": {"field": "gutenberg_id"}}')::text AS total_books
FROM books
WHERE gutenberg_id @@@ pdb.all()
`

type DemoAggregateMetricsRow struct {
	AvgDownloads string
	TotalBooks   string
}

func (q *Queries) DemoAggregateMetrics(ctx context.Context) (DemoAggregateMetricsRow, error) {
	row := q.db.QueryRowContext(ctx, demoAggregateMetrics)
	var i DemoAggregateMetricsRow
	err := row.Scan(&i.AvgDownloads, &i.TotalBooks)
	return i, err
}

const demoBoolean = `-- name: DemoBoolean :many
SELECT
	gutenberg_id::text AS gutenberg_id,
	title,
	author,
	pdb.score(gutenberg_id)::text AS score
FROM books
WHERE content @@@ pdb.boolean(
	must     => ARRAY[pdb.parse('love')],
	must_not => ARRAY[pdb.parse('war')]
)
ORDER BY score DESC
LIMIT $1::int
`

type DemoBooleanRow struct {
	GutenbergID string
	Title       string
	Author      string
	Score       string
}

func (q *Queries) DemoBoolean(ctx context.Context, limitRows int32) ([]DemoBooleanRow, error) {
	rows, err := q.db.QueryContext(ctx, demoBoolean, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DemoBooleanRow
	for rows.Next() {
		var i DemoBooleanRow
		if err := rows.Scan(
			&i.GutenbergID,
			&i.Title,
			&i.Author,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const demoBoosting = `-- name: DemoBoosting :many
SELECT
	gutenberg_id::text AS gutenberg_id,
	title,
	author,
	pdb.score(gutenberg_id)::text AS score
FROM books
WHERE title ||| 'love marriage'::pdb.boost(3)
	OR content ||| 'love marriage'
ORDER BY score DESC
LIMIT $1::int
`

type DemoBoostingRow struct {
	GutenbergID string
	Title       string
	Author      string
	Score       string
}

func (q *Queries) DemoBoosting(ctx context.Context, limitRows int32) ([]DemoBoostingRow, error) {
	rows, err := q.db.QueryContext(ctx, demoBoosting, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DemoBoostingRow
	for rows.Next() {
		var i DemoBoostingRow
		if err := rows.Scan(
			&i.GutenbergID,
			&i.Title,
			&i.Author,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const demoFacets = `-- name: DemoFacets :many
SELECT
	gutenberg_id::text AS gutenberg_id,
	title,
	author,
	pdb.agg('{"value_count": {"field": "gutenberg_id"}}') OVER ()::text AS total_matches
FROM books
WHERE content ||| 'love'
ORDER BY pdb.score(gutenberg_id) DESC
LIMIT 3
`

type DemoFacetsRow struct {
	GutenbergID  string
	Title        string
	Author       string
	TotalMatches string
}

func (q *Queries) DemoFacets(ctx context.Context) ([]DemoFacetsRow, error) {
	rows, err := q.db.QueryContext(ctx, demoFacets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DemoFacetsRow
	for rows.Next() {
		var i DemoFacetsRow
		if err := rows.Scan(
			&i.GutenbergID,
			&i.Title,
			&i.Author,
			&i.TotalMatches,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const demoFiltering = `-- name: DemoFiltering :many
SELECT
	gutenberg_id::text AS gutenberg_id,
	title,
	author,
	download_count::text AS download_count,
	pdb.score(gutenberg_id)::text AS score
FROM books
WHERE content ||| 'love'
	AND download_count > 100
ORDER BY score DESC
LIMIT $1::int
`

type DemoFilteringRow struct {
	GutenbergID   string
	Title         string
	Author        string
	DownloadCount string
	Score         string
}

func (q *Queries) DemoFiltering(ctx context.Context, limitRows int32) ([]DemoFilteringRow, error) {
	rows, err := q.db.QueryContext(ctx, demoFiltering, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DemoFilteringRow
	for rows.Next() {
		var i DemoFilteringRow
		if err := rows.Scan(
			&i.GutenbergID,
			&i.Title,
			&i.Author,
			&i.DownloadCount,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const demoFuzzy = `-- name: DemoFuzzy :many
SELECT
	gutenberg_id::text AS gutenberg_id,
	title,
	author,
	pdb.score(gutenberg_id)::text AS score
FROM books
WHERE content ||| 'marrige'::pdb.fuzzy(2)
ORDER BY score DESC
LIMIT $1::int
`

type DemoFuzzyRow struct {
	GutenbergID string
	Title       string
	Author      string
	Score       string
}

func (q *Queries) DemoFuzzy(ctx context.Context, limitRows int32) ([]DemoFuzzyRow, error) {
	rows, err := q.db.QueryContext(ctx, demoFuzzy, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DemoFuzzyRow
	for rows.Next() {
		var i DemoFuzzyRow
		if err := rows.Scan(
			&i.GutenbergID,
			&i.Title,
			&i.Author,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const demoHighlighting = `-- name: DemoHighlighting :many
SELECT
	gutenberg_id::text AS gutenberg_id,
	title,
	pdb.snippet(content)::text AS snippet
FROM books
WHERE content ||| 'marriage'
ORDER BY pdb.score(gutenberg_id) DESC
LIMIT $1::int
`

type DemoHighlightingRow struct {
	GutenbergID string
	Title       string
	Snippet     string
}

func (q *Queries) DemoHighlighting(ctx context.Context, limitRows int32) ([]DemoHighlightingRow, error) {
	rows, err := q.db.QueryContext(ctx, demoHighlighting, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DemoHighlightingRow
	for rows.Next() {
		var i DemoHighlightingRow
		if err := rows.Scan(&i.GutenbergID, &i.Title, &i.Snippet); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const demoMatchConjunction = `-- name: DemoMatchConjunction :many
SELECT
	gutenberg_id::text AS gutenberg_id,
	title,
	author,
	pdb.score(gutenberg_id)::text AS score
FROM books
WHERE content &&& 'love marriage'
ORDER BY score DESC
LIMIT $1::int
`

type DemoMatchConjunctionRow struct {
	GutenbergID string
	Title       string
	Author      string
	Score       string
}

func (q *Queries) DemoMatchConjunction(ctx context.Context, limitRows int32) ([]DemoMatchConjunctionRow, error) {
	rows, err := q.db.QueryContext(ctx, demoMatchConjunction, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DemoMatchConjunctionRow
	for rows.Next() {
		var i DemoMatchConjunctionRow
		if err := rows.Scan(
			&i.GutenbergID,
			&i.Title,
			&i.Author,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const demoMatchDisjunction = `-- name: DemoMatchDisjunction :many
SELECT
	gutenberg_id::text AS gutenberg_id,
	title,
	author,
	pdb.score(gutenberg_id)::text AS score
FROM books
WHERE content ||| 'love marriage'
ORDER BY score DESC
LIMIT $1::int
`

type DemoMatchDisjunctionRow struct {
	GutenbergID string
	Title       string
	Author      string
	Score       string
}

func (q *Queries) DemoMatchDisjunction(ctx context.Context, limitRows int32) ([]DemoMatchDisjunctionRow, error) {
	rows, err := q.db.QueryContext(ctx, demoMatchDisjunction, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DemoMatchDisjunctionRow
	for rows.Next() {
		var i DemoMatchDisjunctionRow
		if err := rows.Scan(
			&i.GutenbergID,
			&i.Title,
			&i.Author,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const demoPhrase = `-- name: DemoPhrase :many
SELECT
	gutenberg_id::text AS gutenberg_id,
	title,
	author,
	pdb.score(gutenberg_id)::text AS score
FROM books
WHERE content ### 'single man'
ORDER BY score DESC
LIMIT $1::int
`

type DemoPhraseRow struct {
	GutenbergID string
	Title       string
	Author      string
	Score       string
}

func (q *Queries) DemoPhrase(ctx context.Context, limitRows int32) ([]DemoPhraseRow, error) {
	rows, err := q.db.QueryContext(ctx, demoPhrase, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DemoPhraseRow
	for rows.Next() {
		var i DemoPhraseRow
		if err := rows.Scan(
			&i.GutenbergID,
			&i.Title,
			&i.Author,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const demoPhraseWithSlop = `-- name: DemoPhraseWithSlop :many
SELECT
	gutenberg_id::text AS gutenberg_id,
	title,
	author,
	pdb.score(gutenberg_id)::text AS score
FROM books
WHERE content ### 'marriage love'::pdb.slop(2)
ORDER BY score DESC
LIMIT $1::int
`

type DemoPhraseWithSlopRow struct {
	GutenbergID string
	Title       string
	Author      string
	Score       string
}

func (q *Queries) DemoPhraseWithSlop(ctx context.Context, limitRows int32) ([]DemoPhraseWithSlopRow, error) {
	rows, err := q.db.QueryContext(ctx, demoPhraseWithSlop, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DemoPhraseWithSlopRow
	for rows.Next() {
		var i DemoPhraseWithSlopRow
		if err := rows.Scan(
			&i.GutenbergID,
			&i.Title,
			&i.Author,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const demoProximity = `-- name: DemoProximity :many
SELECT
	gutenberg_id::text AS gutenberg_id,
	title,
	author,
	pdb.score(gutenberg_id)::text AS score
FROM books
WHERE content @@@ ('love' ## 5 ## 'marriage')
ORDER BY score DESC
LIMIT $1::int
`

type DemoProximityRow struct {
	GutenbergID string
	Title       string
	Author      string
	Score       string
}

func (q *Queries) DemoProximity(ctx context.Context, limitRows int32) ([]DemoProximityRow, error) {
	rows, err := q.db.QueryContext(ctx, demoProximity, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DemoProximityRow
	for rows.Next() {
		var i DemoProximityRow
		if err := rows.Scan(
			&i.GutenbergID,
			&i.Title,
			&i.Author,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const demoRange = `-- name: DemoRange :many
SELECT
	gutenberg_id::text AS gutenberg_id,
	title,
	author,
	download_count::text AS download_count
FROM books
WHERE gutenberg_id @@@ pdb.all()
	AND download_count BETWEEN 5000 AND 100000
ORDER BY download_count DESC
LIMIT $1::int
`

type DemoRangeRow struct {
	GutenbergID   string
	Title         string
	Author        string
	DownloadCount string
}

func (q *Queries) DemoRange(ctx context.Context, limitRows int32) ([]DemoRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, demoRange, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DemoRangeRow
	for rows.Next() {
		var i DemoRangeRow
		if err := rows.Scan(
			&i.GutenbergID,
			&i.Title,
			&i.Author,
			&i.DownloadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const demoRegex = `-- name: DemoRegex :many
SELECT
	gutenberg_id::text AS gutenberg_id,
	title,
	author
FROM books
WHERE author @@@ pdb.regex('bront.*')
LIMIT $1::int
`

type DemoRegexRow struct {
	GutenbergID string
	Title       string
	Author      string
}

func (q *Queries) DemoRegex(ctx context.Context, limitRows int32) ([]DemoRegexRow, error) {
	rows, err := q.db.QueryContext(ctx, demoRegex, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DemoRegexRow
	for rows.Next() {
		var i DemoRegexRow
		if err := rows.Scan(&i.GutenbergID, &i.Title, &i.Author); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const demoTermLanguage = `-- name: DemoTermLanguage :many
SELECT
	gutenberg_id::text AS gutenberg_id,
	title,
	author,
	language
FROM books
WHERE language === 'en'
LIMIT $1::int
`

type DemoTermLanguageRow struct {
	GutenbergID string
	Title       string
	Author      string
	Language    string
}

func (q *Queries) DemoTermLanguage(ctx context.Context, limitRows int32) ([]DemoTermLanguageRow, error) {
	rows, err := q.db.QueryContext(ctx, demoTermLanguage, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DemoTermLanguageRow
	for rows.Next() {
		var i DemoTermLanguageRow
		if err := rows.Scan(
			&i.GutenbergID,
			&i.Title,
			&i.Author,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
