// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
	"time"
)

type Book struct {
	GutenbergID   int64
	Title         string
	Author        string
	Language      string
	Subjects      json.RawMessage
	Bookshelves   json.RawMessage
	DownloadCount int32
	SourceUrl     string
	TextUrl       string
	Content       string
	ContentBytes  int64
	ImportedAt    time.Time
}
