// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package sqlc

import (
	"context"
)

const searchBooks = `-- name: SearchBooks :many
SELECT
	gutenberg_id,
	title,
	author,
	language,
	download_count,
	content_bytes,
	pdb.score(gutenberg_id)::double precision AS score,
	CASE
		WHEN $1::boolean THEN pdb.snippet(content)::text
		ELSE ''::text
	END AS snippet
FROM books
WHERE (
	CASE
		WHEN $2::boolean THEN (
			title &&& $3::text
			OR author &&& $3::text
			OR content &&& $3::text
		)
		ELSE (
			title ||| $3::text
			OR author ||| $3::text
			OR content ||| $3::text
		)
	END
)
AND (
	$4::text = ''
	OR author ILIKE $4::text
)
AND (
	$5::text = ''
	OR language = $5::text
)
ORDER BY score DESC, download_count DESC
LIMIT $6::int
`

type SearchBooksParams struct {
	IncludeSnippet bool
	UseConjunction bool
	QueryText      string
	AuthorPattern  string
	LanguageFilter string
	LimitRows      int32
}

type SearchBooksRow struct {
	GutenbergID   int64
	Title         string
	Author        string
	Language      string
	DownloadCount int32
	ContentBytes  int64
	Score         float64
	Snippet       string
}

func (q *Queries) SearchBooks(ctx context.Context, arg SearchBooksParams) ([]SearchBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, searchBooks,
		arg.IncludeSnippet,
		arg.UseConjunction,
		arg.QueryText,
		arg.AuthorPattern,
		arg.LanguageFilter,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBooksRow
	for rows.Next() {
		var i SearchBooksRow
		if err := rows.Scan(
			&i.GutenbergID,
			&i.Title,
			&i.Author,
			&i.Language,
			&i.DownloadCount,
			&i.ContentBytes,
			&i.Score,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
