// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SensorDatum struct {
	Time        pgtype.Timestamptz
	SensorID    string
	Temperature *float64
	Humidity    *float64
}

type SensorHourly struct {
	Bucket      pgtype.Timestamptz
	SensorID    string
	AvgTemp     float64
	MinTemp     float64
	MaxTemp     float64
	SampleCount int64
}

type StockPrice struct {
	Time   pgtype.Timestamptz
	Symbol string
	Price  *float64
	Volume *int32
}
