// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: timescaledb.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSensorDataColumnstorePolicy = `-- name: AddSensorDataColumnstorePolicy :exec
CALL add_columnstore_policy(
    'sensor_data',
    after => INTERVAL '7 days',
    if_not_exists => true
)
`

func (q *Queries) AddSensorDataColumnstorePolicy(ctx context.Context) error {
	_, err := q.db.Exec(ctx, addSensorDataColumnstorePolicy)
	return err
}

const addSensorDataRetentionPolicy = `-- name: AddSensorDataRetentionPolicy :exec
SELECT add_retention_policy(
    'sensor_data',
    drop_after => INTERVAL '30 days',
    if_not_exists => true
)
`

func (q *Queries) AddSensorDataRetentionPolicy(ctx context.Context) error {
	_, err := q.db.Exec(ctx, addSensorDataRetentionPolicy)
	return err
}

const addSensorHourlyCaggPolicy = `-- name: AddSensorHourlyCaggPolicy :exec
SELECT add_continuous_aggregate_policy(
    'sensor_hourly',
    start_offset => INTERVAL '2 days',
    end_offset => INTERVAL '10 minutes',
    schedule_interval => INTERVAL '10 minutes',
    if_not_exists => true
)
`

func (q *Queries) AddSensorHourlyCaggPolicy(ctx context.Context) error {
	_, err := q.db.Exec(ctx, addSensorHourlyCaggPolicy)
	return err
}

const analyzeSensorData = `-- name: AnalyzeSensorData :exec
ANALYZE sensor_data
`

func (q *Queries) AnalyzeSensorData(ctx context.Context) error {
	_, err := q.db.Exec(ctx, analyzeSensorData)
	return err
}

const createSensorDataHypertable = `-- name: CreateSensorDataHypertable :exec
SELECT create_hypertable('sensor_data', by_range('time'), if_not_exists => TRUE)
`

func (q *Queries) CreateSensorDataHypertable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createSensorDataHypertable)
	return err
}

const createSensorDataIndex = `-- name: CreateSensorDataIndex :exec
CREATE INDEX IF NOT EXISTS idx_sensor_data_sensor_time
ON sensor_data (sensor_id, time DESC)
`

func (q *Queries) CreateSensorDataIndex(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createSensorDataIndex)
	return err
}

const createSensorDataTable = `-- name: CreateSensorDataTable :exec
CREATE TABLE IF NOT EXISTS sensor_data (
    time        TIMESTAMPTZ NOT NULL,
    sensor_id   TEXT NOT NULL,
    temperature DOUBLE PRECISION,
    humidity    DOUBLE PRECISION,
    PRIMARY KEY (time, sensor_id)
)
`

func (q *Queries) CreateSensorDataTable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createSensorDataTable)
	return err
}

const createSensorHourlyCagg = `-- name: CreateSensorHourlyCagg :exec
CREATE MATERIALIZED VIEW IF NOT EXISTS sensor_hourly
WITH (timescaledb.continuous) AS
SELECT
    time_bucket('1 hour', time) AS bucket,
    sensor_id,
    avg(temperature) AS avg_temp,
    min(temperature) AS min_temp,
    max(temperature) AS max_temp,
    avg(humidity) AS avg_humidity,
    count(*) AS sample_count
FROM sensor_data
GROUP BY bucket, sensor_id
`

func (q *Queries) CreateSensorHourlyCagg(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createSensorHourlyCagg)
	return err
}

const createStockPricesHypertable = `-- name: CreateStockPricesHypertable :exec
SELECT create_hypertable('stock_prices', by_range('time'), if_not_exists => TRUE)
`

func (q *Queries) CreateStockPricesHypertable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createStockPricesHypertable)
	return err
}

const createStockPricesIndex = `-- name: CreateStockPricesIndex :exec
CREATE INDEX IF NOT EXISTS idx_stock_prices_symbol_time
ON stock_prices (symbol, time DESC)
`

func (q *Queries) CreateStockPricesIndex(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createStockPricesIndex)
	return err
}

const createStockPricesTable = `-- name: CreateStockPricesTable :exec
CREATE TABLE IF NOT EXISTS stock_prices (
    time   TIMESTAMPTZ NOT NULL,
    symbol TEXT NOT NULL,
    price  DOUBLE PRECISION,
    volume INTEGER
)
`

func (q *Queries) CreateStockPricesTable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createStockPricesTable)
	return err
}

const dropSensorDataTable = `-- name: DropSensorDataTable :exec
DROP TABLE IF EXISTS sensor_data CASCADE
`

func (q *Queries) DropSensorDataTable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, dropSensorDataTable)
	return err
}

const dropSensorHourlyView = `-- name: DropSensorHourlyView :exec
DROP MATERIALIZED VIEW IF EXISTS sensor_hourly CASCADE
`

func (q *Queries) DropSensorHourlyView(ctx context.Context) error {
	_, err := q.db.Exec(ctx, dropSensorHourlyView)
	return err
}

const dropStockPricesTable = `-- name: DropStockPricesTable :exec
DROP TABLE IF EXISTS stock_prices CASCADE
`

func (q *Queries) DropStockPricesTable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, dropStockPricesTable)
	return err
}

const enableTimescaleExtension = `-- name: EnableTimescaleExtension :exec
CREATE EXTENSION IF NOT EXISTS timescaledb
`

func (q *Queries) EnableTimescaleExtension(ctx context.Context) error {
	_, err := q.db.Exec(ctx, enableTimescaleExtension)
	return err
}

const getFiveMinuteTemperatureStatsLastHour = `-- name: GetFiveMinuteTemperatureStatsLastHour :many
SELECT time_bucket('5 minutes', time)::timestamptz AS bucket,
       AVG(temperature) AS avg_temp,
       COALESCE(MIN(temperature), 0)::float8 AS min_temp,
       COALESCE(MAX(temperature), 0)::float8 AS max_temp
FROM sensor_data
WHERE time > NOW() - INTERVAL '1 hour'
GROUP BY bucket
ORDER BY bucket DESC
LIMIT 5
`

type GetFiveMinuteTemperatureStatsLastHourRow struct {
	Bucket  pgtype.Timestamptz
	AvgTemp float64
	MinTemp float64
	MaxTemp float64
}

func (q *Queries) GetFiveMinuteTemperatureStatsLastHour(ctx context.Context) ([]GetFiveMinuteTemperatureStatsLastHourRow, error) {
	rows, err := q.db.Query(ctx, getFiveMinuteTemperatureStatsLastHour)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFiveMinuteTemperatureStatsLastHourRow
	for rows.Next() {
		var i GetFiveMinuteTemperatureStatsLastHourRow
		if err := rows.Scan(
			&i.Bucket,
			&i.AvgTemp,
			&i.MinTemp,
			&i.MaxTemp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGapfilledSensorTemperature = `-- name: GetGapfilledSensorTemperature :many
SELECT time_bucket_gapfill(
           '10 minutes',
           time,
           start => NOW() - INTERVAL '30 minutes',
           finish => NOW()
    )::timestamptz AS bucket,
       sensor_id,
    CASE
        WHEN COUNT(temperature) = 0 THEN NULL::float8
        ELSE AVG(temperature)::float8
    END AS avg_temp
FROM sensor_data
WHERE sensor_id = $1
    AND time >= NOW() - INTERVAL '30 minutes'
    AND time < NOW()
GROUP BY bucket, sensor_id
ORDER BY bucket DESC
LIMIT 5
`

type GetGapfilledSensorTemperatureRow struct {
	Bucket   pgtype.Timestamptz
	SensorID string
	AvgTemp  float64
}

func (q *Queries) GetGapfilledSensorTemperature(ctx context.Context, sensorID string) ([]GetGapfilledSensorTemperatureRow, error) {
	rows, err := q.db.Query(ctx, getGapfilledSensorTemperature, sensorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGapfilledSensorTemperatureRow
	for rows.Next() {
		var i GetGapfilledSensorTemperatureRow
		if err := rows.Scan(&i.Bucket, &i.SensorID, &i.AvgTemp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHourlyAverageTemperatureLast24h = `-- name: GetHourlyAverageTemperatureLast24h :many
SELECT time_bucket('1 hour', time)::timestamptz AS hour,
       AVG(temperature) AS avg_temp
FROM sensor_data
WHERE time > NOW() - INTERVAL '24 hours'
GROUP BY hour
ORDER BY hour DESC
LIMIT 10
`

type GetHourlyAverageTemperatureLast24hRow struct {
	Hour    pgtype.Timestamptz
	AvgTemp float64
}

func (q *Queries) GetHourlyAverageTemperatureLast24h(ctx context.Context) ([]GetHourlyAverageTemperatureLast24hRow, error) {
	rows, err := q.db.Query(ctx, getHourlyAverageTemperatureLast24h)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHourlyAverageTemperatureLast24hRow
	for rows.Next() {
		var i GetHourlyAverageTemperatureLast24hRow
		if err := rows.Scan(&i.Hour, &i.AvgTemp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestReadingsPerSensor = `-- name: GetLatestReadingsPerSensor :many
SELECT DISTINCT ON (sensor_id)
       sensor_id,
       time,
       temperature,
       humidity
FROM sensor_data
ORDER BY sensor_id, time DESC
`

type GetLatestReadingsPerSensorRow struct {
	SensorID    string
	Time        pgtype.Timestamptz
	Temperature *float64
	Humidity    *float64
}

func (q *Queries) GetLatestReadingsPerSensor(ctx context.Context) ([]GetLatestReadingsPerSensorRow, error) {
	rows, err := q.db.Query(ctx, getLatestReadingsPerSensor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestReadingsPerSensorRow
	for rows.Next() {
		var i GetLatestReadingsPerSensorRow
		if err := rows.Scan(
			&i.SensorID,
			&i.Time,
			&i.Temperature,
			&i.Humidity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSensorHourlyAggregateLast7Days = `-- name: GetSensorHourlyAggregateLast7Days :many
SELECT
    bucket,
    sensor_id,
    round(avg_temp::numeric, 2)::float8 AS avg_temp,
    round(min_temp::numeric, 2)::float8 AS min_temp,
    round(max_temp::numeric, 2)::float8 AS max_temp,
    sample_count
FROM sensor_hourly
WHERE bucket > now() - interval '7 days'
ORDER BY bucket DESC, sensor_id
LIMIT 10
`

type GetSensorHourlyAggregateLast7DaysRow struct {
	Bucket      pgtype.Timestamptz
	SensorID    string
	AvgTemp     float64
	MinTemp     float64
	MaxTemp     float64
	SampleCount int64
}

func (q *Queries) GetSensorHourlyAggregateLast7Days(ctx context.Context) ([]GetSensorHourlyAggregateLast7DaysRow, error) {
	rows, err := q.db.Query(ctx, getSensorHourlyAggregateLast7Days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSensorHourlyAggregateLast7DaysRow
	for rows.Next() {
		var i GetSensorHourlyAggregateLast7DaysRow
		if err := rows.Scan(
			&i.Bucket,
			&i.SensorID,
			&i.AvgTemp,
			&i.MinTemp,
			&i.MaxTemp,
			&i.SampleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSensorStatistics = `-- name: GetSensorStatistics :many
SELECT sensor_id,
       COUNT(*) AS count,
       AVG(temperature) AS avg_temp,
       AVG(humidity) AS avg_humidity
FROM sensor_data
GROUP BY sensor_id
ORDER BY sensor_id
`

type GetSensorStatisticsRow struct {
	SensorID    string
	Count       int64
	AvgTemp     float64
	AvgHumidity float64
}

func (q *Queries) GetSensorStatistics(ctx context.Context) ([]GetSensorStatisticsRow, error) {
	rows, err := q.db.Query(ctx, getSensorStatistics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSensorStatisticsRow
	for rows.Next() {
		var i GetSensorStatisticsRow
		if err := rows.Scan(
			&i.SensorID,
			&i.Count,
			&i.AvgTemp,
			&i.AvgHumidity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockPriceSummaryBySymbol = `-- name: GetStockPriceSummaryBySymbol :many
SELECT symbol,
       COUNT(*) AS count,
       AVG(price) AS avg_price,
    COALESCE(MIN(price), 0)::float8 AS min_price,
    COALESCE(MAX(price), 0)::float8 AS max_price,
       SUM(volume) AS total_volume
FROM stock_prices
GROUP BY symbol
ORDER BY symbol
`

type GetStockPriceSummaryBySymbolRow struct {
	Symbol      string
	Count       int64
	AvgPrice    float64
	MinPrice    float64
	MaxPrice    float64
	TotalVolume int64
}

func (q *Queries) GetStockPriceSummaryBySymbol(ctx context.Context) ([]GetStockPriceSummaryBySymbolRow, error) {
	rows, err := q.db.Query(ctx, getStockPriceSummaryBySymbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStockPriceSummaryBySymbolRow
	for rows.Next() {
		var i GetStockPriceSummaryBySymbolRow
		if err := rows.Scan(
			&i.Symbol,
			&i.Count,
			&i.AvgPrice,
			&i.MinPrice,
			&i.MaxPrice,
			&i.TotalVolume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockPriceTrendsLast6Hours = `-- name: GetStockPriceTrendsLast6Hours :many
SELECT symbol,
    time_bucket('1 hour', time)::timestamptz AS hour,
       AVG(price) AS avg_price
FROM stock_prices
WHERE time > NOW() - INTERVAL '6 hours'
GROUP BY symbol, hour
ORDER BY symbol, hour DESC
LIMIT 15
`

type GetStockPriceTrendsLast6HoursRow struct {
	Symbol   string
	Hour     pgtype.Timestamptz
	AvgPrice float64
}

func (q *Queries) GetStockPriceTrendsLast6Hours(ctx context.Context) ([]GetStockPriceTrendsLast6HoursRow, error) {
	rows, err := q.db.Query(ctx, getStockPriceTrendsLast6Hours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStockPriceTrendsLast6HoursRow
	for rows.Next() {
		var i GetStockPriceTrendsLast6HoursRow
		if err := rows.Scan(&i.Symbol, &i.Hour, &i.AvgPrice); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSampleSensorData = `-- name: InsertSampleSensorData :exec
INSERT INTO sensor_data (time, sensor_id, temperature, humidity)
SELECT
    ts,
    'sensor_' || ((random() * 4)::int + 1),
    18 + random() * 12,
    35 + random() * 25
FROM generate_series(
    now() - interval '24 hours',
    now(),
    interval '10 seconds'
) ts
`

func (q *Queries) InsertSampleSensorData(ctx context.Context) error {
	_, err := q.db.Exec(ctx, insertSampleSensorData)
	return err
}

const insertStockPrice = `-- name: InsertStockPrice :exec
INSERT INTO stock_prices (time, symbol, price, volume)
VALUES ($1, $2, $3, $4)
`

type InsertStockPriceParams struct {
	Time   pgtype.Timestamptz
	Symbol string
	Price  *float64
	Volume *int32
}

func (q *Queries) InsertStockPrice(ctx context.Context, arg InsertStockPriceParams) error {
	_, err := q.db.Exec(ctx, insertStockPrice,
		arg.Time,
		arg.Symbol,
		arg.Price,
		arg.Volume,
	)
	return err
}

const setSensorDataChunkInterval = `-- name: SetSensorDataChunkInterval :exec
SELECT set_chunk_time_interval('sensor_data', INTERVAL '1 day')
`

func (q *Queries) SetSensorDataChunkInterval(ctx context.Context) error {
	_, err := q.db.Exec(ctx, setSensorDataChunkInterval)
	return err
}

const setSensorDataColumnstore = `-- name: SetSensorDataColumnstore :exec
ALTER TABLE sensor_data
SET (
    timescaledb.enable_columnstore = true,
    timescaledb.compress_segmentby = 'sensor_id',
    timescaledb.compress_orderby = 'time DESC'
)
`

func (q *Queries) SetSensorDataColumnstore(ctx context.Context) error {
	_, err := q.db.Exec(ctx, setSensorDataColumnstore)
	return err
}
